(defproject com.amazonaws/aws-apigateway-importer "1.0.3-SNAPSHOT"
  :parent [org.sonatype.oss/oss-parent "7"]
;;   :resource-paths ["${project.basedir}"]
  :source-paths ["src"]
  :test-paths ["tst"]
  :dependencies [[com.amazonaws/aws-apigateway-sdk-java "1.1.1"]
                 [com.amazonaws/aws-hal-client-java "1.3.0"]
                 [com.amazonaws/aws-java-sdk-core "[1.8.6,2.0)"]
                 [org.glassfish/javax.json "1.0-b06"]
                 [de.weltraumschaf.commons/jcommander "2.0.0"]
                 [com.google.inject/guice "4.0"]
                 [log4j "1.2.14"]
                 [io.swagger/swagger-parser "1.0.17"]
                 [io.swagger/swagger-compat-spec-parser "1.0.17"]
                 [io.swagger/swagger-core "1.5.8"]
                 [org.raml/raml-parser "0.8.11"]
                 [org.apache.commons/commons-io "1.3.2"]
                 [org.apache.commons/commons-lang3 "3.4"]
                 [com.google.guava/guava "18.0"]
                 [com.amazonaws/aws-java-sdk "1.9.6"]
                 [org.apache.httpcomponents/httpclient "4.3.3"]
                 [junit "4.10"]
                 [org.mockito/mockito-all "2.0.2-beta"]
                 [com.fasterxml.jackson.core/jackson-annotations "2.5.0"]
                 [com.fasterxml.jackson.core/jackson-core "2.5.0"]])
